# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.godaddy.com/status_registered_bis.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'rubygems'

#require './spec_helper'
require 'whois'
require 'whois/record/parser/whois.godaddy.com'
require 'uk/bl/wa/whois/convert'

part = Whois::Record::Part.new(body: content)
response = Whois::Record::Parser::WhoisGodaddyCom.new(part)

puts(response.technical_contacts[0])
createJavaContact(response.technical_contacts[0])
